### ISSUE TITLE
Implement community detection

### ISSUE THREAD

**Issue by mizvol** [ayman-mezghani/Wikipedia-Graph-Processor#1]
Use the Louvain algorithm to extract communities from a graph.

Load .gexf graph in NetworkX and use [`community.best_partition`](https://python-louvain.readthedocs.io/en/latest/api.html)

**Comment by ayman-mezghani** [comment]
Done using best_partition

**Comment by mizvol** [comment]
@ayman-mezghani You could also push the code in this repo.

**Comment by ayman-mezghani** [comment]
I just pushed the code. I hope it doesn't matter that it's a notebook

**Comment by mizvol** [comment]
Sure. Just two things to consider. First, give it a comprehensible name. Second, avoid versioning outputs. Read more here: [https://nextjournal.com/schmudde/how-to-version-control-jupyter](https://nextjournal.com/schmudde/how-to-version-control-jupyter)

**Comment by ayman-mezghani** [comment]
Renamed the file and cleared the output before commit

**Comment by ayman-mezghani** [comment]
Note to self: implement Leiden instead of Louvain. https://www.nature.com/articles/s41598-019-41695-z https://pypi.org/project/leidenalg/

**Comment by ayman-mezghani** [comment]
Implemented Leiden. implemented some adapters to convert to igraph and then to translate output to desired format. I remark that it yields a lot less communities
